name: Build Push Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test-runner:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2

      - name: Verify AWS Login
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Docker Version
        run: docker --version

      - name: Build UI Image
        run: |
          docker build \
          -t 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:ui-github-v2 \
          ./ui-web-app-reactjs

      - name: Push UI Image
        run: |
          docker push \
          663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:ui-github-v2

      - name: Build Zuul Image
        run: |
          docker build \
          -t 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:zuul-github-v2 \
          ./zuul-api-gateway

      - name: Push Zuul Image
        run: |
          docker push \
          663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:zuul-github-v2

      - name: Build Offers Image
        run: |
          docker build \
          -t 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:offers-github-v2 \
          ./offers-microservice-spring-boot

      - name: Push Offers Image
        run: |
          docker push \
          663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:offers-github-v2

      - name: Build Shoes Image
        run: |
          docker build \
          -t 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:shoes-github-v2 \
          ./shoes-microservice-spring-boot

      - name: Push Shoes Image
        run: |
          docker push \
          663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:shoes-github-v2

      - name: Build Wishlist Image
        run: |
          docker build \
          -t 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:wishlist-github-v2 \
          ./wishlist-microservice-python

      - name: Push Wishlist Image
        run: |
          docker push \
          663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:wishlist-github-v2

      - name: Build Cart Image
        run: |
          docker build \
          -t 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:cart-github-v2 \
          ./cart-microservice-nodejs

      - name: Push Cart Image
        run: |
          docker push \
          663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:cart-github-v2

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2 Successfully"
            hostname
            whoami
            docker --version

      - name: Deploy UI Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            aws ecr get-login-password \
            --region ap-south-2 \
            | docker login \
            --username AWS \
            --password-stdin \
            663566123253.dkr.ecr.ap-south-2.amazonaws.com

            docker pull 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:ui-github-v2
            docker pull 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:zuul-github-v2
            docker pull 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:offers-github-v2
            docker pull 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:shoes-github-v2
            docker pull 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:wishlist-github-v2
            docker pull 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:cart-github-v2


            docker stop ui || true
            docker stop zuul || true
            docker stop offers || true
            docker stop shoes || true
            docker stop wishlist || true
            docker stop cart || true

       
            docker rm ui || true
            docker rm zuul || true
            docker rm offers || true
            docker rm shoes || true
            docker rm wishlist || true
            docker rm cart || true


            docker image prune -f

            

            docker run -d \
              --network micro-net \
              --name offers \
              -p 1001:1001 \
              663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:offers-github-v2

            docker run -d \
              --network micro-net \
              --name shoes \
              -p 1002:1002 \
              663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:shoes-github-v2
              
            docker run -d \
              --network micro-net \
              --name wishlist \
              -p 1003:1003 \
              663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:wishlist-github-v2

            docker run -d \
              --network micro-net \
              --name cart \
              -p 1004:1004 \
              663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:cart-github-v2
            
            docker run -d \
              --network micro-net \
              --name zuul \
              -p 9999:9999 \
              663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:zuul-github-v2

            docker run -d \
              --network micro-net \
              --name ui \
              -p 8080:8080 \
              -e HOST=0.0.0.0 \
              -e PORT=8080 \
              -e WDS_SOCKET_PORT=8080 \
              663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:ui-github-v2

            docker ps
            docker ps -a
            docker network inspect micro-net

      - name: Print Message
        run: echo "GitHub Actions is working!"