name: Build Push Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test-runner:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2

      - name: Verify AWS Login
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Docker Version
        run: docker --version

      - name: Build UI Image
        run: |
          docker build \
          -t 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:ui-github-v2 \
          ./ui-web-app-reactjs

      - name: Push UI Image
        run: |
          docker push \
          663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:ui-github-v2

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2 Successfully"
            hostname
            whoami
            docker --version

      - name: Deploy UI Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            docker pull 663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:ui-github

            docker stop ui || true

            docker rm ui || true

            docker run -d \
              --network micro-net \
              --name ui \
              -p 8080:8080 \
              -e HOST=0.0.0.0 \
              -e PORT=8080 \
              -e WDS_SOCKET_PORT=8080 \
              663566123253.dkr.ecr.ap-south-2.amazonaws.com/devops:ui-github

            docker ps

      - name: Print Message
        run: echo "GitHub Actions is working!"